#!/bin/bash

for crt in /local/jdk/certs/*.crt; do
	if [ -f $crt ]; then
		for f in /local/jdk/jdk*; do
			cbase=`basename $crt .crt`

			for cafile in $f/jre/lib/security/cacerts $f/lib/security/cacerts ]; do
				if [ -e $cafile ]; then
					$f/bin/keytool -import -trustcacerts \
						-keystore $cafile \
						-storepass changeit -noprompt \
						-alias $cbase -file $crt
				fi
			done
		done
	fi
done
