#!/bin/bash

for f in /local/jdk/jdk*; do
	for crt in /local/jdk/certs/*.crt; do
		cbase=`basename $crt .crt`

		for cafile in $f/jre/lib/security/cacerts $f/lib/security/cacerts ]; do
			if [ -e $cafile ]; then
				$f/bin/keytool -import -trustcacerts \
					-keystore $cafile \
					-storepass changeit -noprompt \
					-alias $cbase -file $crt
			fi
		done
	done
done
