#!/bin/sh -x

mkdir -p tar

GEN=6
BITS=64

BASE=http://download.oracle.com/otn-pub/java/jdk

case "$GEN-$BITS" in
	6-64)
		URL=$BASE/6u45-b06/jdk-6u45-linux-x64.bin
		FILE=`basename $URL`
		;;
	6-32)
		URL=$BASE/6u45-b06/jdk-6u45-linux-i586.bin
		FILE=`basename $URL`
		;;
	*)
		echo "Undefined gen-bits."
		;;
esac

WGET='wget --no-cookies --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com"'

if [ ! -e tar/$FILE ]; then
$WGET $URL -O tar/$FILE
fi

rm -f /etc/profile.d/jdk.sh
rm -f /etc/profile.d/java-home.sh
cp java-home.sh /etc/profile.d/java-home.sh
chmod 755 /etc/profile.d/java-home.sh
