#!/bin/bash

umask 077
cd /local/jdk
mkdir -p tar

WHICH="$1"
if [ "x$WHICH" = "x" ]; then
	#echo "Usage: $0 [8-64|11-64|21-64]"
	#exit 1
	WHICH="21-64"
fi
echo "Setting up for: $WHICH"


case "$WHICH" in
	21-64)
		URL=https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
		FILE=`basename $URL`
		TGT=jdk-21.0.1+12
		SUFFIX=""
		;;
	11-64)
		URL=https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz
		FILE=`basename $URL`
		TGT=jdk-11.0.21+9
		SUFFIX=""
		;;
	8-64)
		URL=https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u332-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u332b09.tar.gz
		FILE=`basename $URL`
		TGT=jdk8u332-b09
		SUFFIX=""
		;;
	oracle8-64)
		URL=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
		FILE=`basename $URL`
		TGT=jdk1.8.0_181
		SUFFIX=""
		# http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
		CRYPTO_BASE=http://download.oracle.com/otn-pub/java/jce
		CRYPTO_URL=$CRYPTO_BASE/8/jce_policy-8.zip
		CRYPTO_FILE=`basename $CRYPTO_URL`
		CRYPTO_TGT=UnlimitedJCEPolicyJDK8
		;;
	*)
		echo "Undefined gen-bits."
		exit 1
		;;
esac

if [ ! -e /usr/bin/curl ]; then
	if [ ! -e tar/$FILE ]; then
		wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
		$URL -O tar/$FILE
	fi

	if [ "x$CRYPTO_FILE" != "x" ]; then
		if [ ! -e tar/$CRYPTO_FILE ]; then
			wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
			$CRYPTO_URL -O tar/$CRYPTO_FILE
		fi
	fi

else

	if [ ! -e tar/$FILE ]; then
		curl -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
		$URL -o tar/$FILE
	fi

	if [ "x$CRYPTO_FILE" != "x" ]; then
		if [ ! -e tar/$CRYPTO_FILE ]; then
			curl -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
			$CRYPTO_URL -o tar/$CRYPTO_FILE
		fi
	fi
fi


if [ ! -e "${TGT}${SUFFIX}" ]; then
	unset DISPLAY
	chmod 755 tar/$FILE
	rm -rf tmpextract
	mkdir -p tmpextract
	cd tmpextract
	case $FILE in
		*.bin)
			../tar/$FILE
			;;
		*.tar.gz)
			tar -xzf ../tar/$FILE
			;;
	esac
	cd ..
	mv tmpextract/$TGT ${TGT}${SUFFIX}
	rm -rf tmpextract
fi

rm -f latest${SUFFIX}
ln -s $TGT latest${SUFFIX}

if [ "x$CRYPTO_FILE" != "x" ]; then
	echo "Installing crypto policy extensions..."
	rm -rf tmpextract
	mkdir -p tmpextract
	cd tmpextract
	unzip ../tar/$CRYPTO_FILE
	cd ..
	cp tmpextract/$CRYPTO_TGT/* /local/jdk/$TGT/jre/lib/security/
	rm -rf tmpextract
fi

./add-local-certs

if [ -e /etc/profile.d ]; then
	rm -f /etc/profile.d/jdk.sh
	rm -f /etc/profile.d/java-home.sh
	cp java-home.sh /etc/profile.d/java-home.sh
	chmod 755 /etc/profile.d/java-home.sh
fi

chown -R root:root /local/jdk
chmod -R ugo+rX /local/jdk
