#!/bin/sh

umask 077
cd /local/jdk
mkdir -p tar

WHICH="$1"
if [ "$WHICH" == "" ]; then
	#echo "Usage: $0 [7-64|8-64]"
	#exit 1
	WHICH="8-64"
fi

BASE=http://download.oracle.com/otn-pub/java/jdk
CRYPTO_BASE=http://download.oracle.com/otn-pub/java/jce

case "$WHICH" in
	8-64)
		# http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz
		URL=$BASE/8u65-b17/jdk-8u65-linux-x64.tar.gz
		FILE=`basename $URL`
		TGT=jdk1.8.0_65
		SUFFIX=""
		# http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
		CRYPTO_URL=$CRYPTO_BASE/8/jce_policy-8.zip
		CRYPTO_FILE=`basename $CRYPTO_URL`
		CRYPTO_TGT=UnlimitedJCEPolicyJDK8
		;;
	8-32)
		# http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-i586.tar.gz
		URL=$BASE/8u65-b17/jdk-8u65-linux-i586.tar.gz
		FILE=`basename $URL`
		TGT=jdk1.8.0_65
		SUFFIX="-32"
		# http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
		CRYPTO_URL=$CRYPTO_BASE/8/jce_policy-8.zip
		CRYPTO_FILE=`basename $CRYPTO_URL`
		CRYPTO_TGT=UnlimitedJCEPolicyJDK8
		;;
	7-64)
		URL=$BASE/7u79-b15/jdk-7u79-linux-x64.tar.gz
		FILE=`basename $URL`
		TGT=jdk1.7.0_79
		SUFFIX=""
		CRYPTO_URL=$CRYPTO_BASE/7/UnlimitedJCEPolicyJDK7.zip
		CRYPTO_FILE=`basename $CRYPTO_URL`
		CRYPTO_TGT=UnlimitedJCEPolicy
		;;
	*)
		echo "Undefined gen-bits."
		exit 1
		;;
esac

if [ ! -e /usr/bin/curl ]; then
if [ ! -e tar/$FILE ]; then
	wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
	$URL -O tar/$FILE
fi

if [ ! -e tar/$CRYPTO_FILE ]; then
	wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
	$CRYPTO_URL -O tar/$CRYPTO_FILE
fi

else

if [ ! -e tar/$FILE ]; then
	curl -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
	$URL -o tar/$FILE
fi

if [ ! -e tar/$CRYPTO_FILE ]; then
	curl -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
	$CRYPTO_URL -o tar/$CRYPTO_FILE
fi

fi


if [ ! -e "${TGT}${SUFFIX}" ]; then
	unset DISPLAY
	chmod 755 tar/$FILE
	rm -rf tmpextract
	mkdir -p tmpextract
	cd tmpextract
	case $FILE in
		*.bin)
			../tar/$FILE
			;;
		*.tar.gz)
			tar -xzf ../tar/$FILE
			;;
	esac
	cd ..
	mv tmpextract/$TGT ${TGT}${SUFFIX}
	rm -rf tmpextract
fi

case $FILE in
	*1.7*)
		rm -f jdk1.7${SUFFIX}
		ln -s $TGT jdk1.7${SUFFIX}
		;;
	*1.8*)
		rm -f jdk1.7${SUFFIX}
		ln -s $TGT jdk1.7${SUFFIX}
		;;
esac

rm -f latest${SUFFIX}
ln -s $TGT latest${SUFFIX}

echo "Installing crypto policy extensions..."
rm -rf tmpextract
mkdir -p tmpextract
cd tmpextract
unzip ../tar/$CRYPTO_FILE
cd ..
cp tmpextract/$CRYPTO_TGT/* /local/jdk/$TGT/jre/lib/security/
rm -rf tmpextract

./add-local-certs

if [ -e /etc/profile.d ]; then
rm -f /etc/profile.d/jdk.sh
rm -f /etc/profile.d/java-home.sh
cp java-home.sh /etc/profile.d/java-home.sh
chmod 755 /etc/profile.d/java-home.sh
fi

chown -R root:root /local/jdk
chmod -R ugo+rX /local/jdk
